add route and css for my projcet
misikir21/mama pull request #6
Opened 2023-08-30 15:56 UTC by misikir21

1. Add 3 routes to make the site real SPA 
2. Used react CSS modules for styling
3. Make sure project requirements met
4. For every page, you should create a <Route>

2023-08-30 16:46 UTC, Efiamotu-1 requested changes
Hi @misikir21 , 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-30 16:46 UTC, Efiamotu-1 commented on src/route/calculator.js
- >* Project Requirement
![rr](https://github.com/misikir21/mama/assets/89055502/f244b379-15f3-4a6c-81f9-ed0f0938195b)
- [ ] From the above project requirement you are required to make use of the `react router` library which provides you with routes to manage and display different pages of your application, visit this [link](https://reactrouter.com/en/main) to learn more about it, however to make use of this npm package in your application you are to install it using this command `npm I react-router-dom`. After installing you are to create these routes in your application, see the code snippet below for example 
- * code snippet
```javascript
import React from 'react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import Layout from '../components/Layout';
import Home from '../components/Home';
import Calculator from '../components/Calculator';
import Quote from '../components/Quote';

function App() {
  return (
    <div className="app">
      <BrowserRouter>
        <Routes>
          <Route path="/" element={<Layout />}>
            <Route index element={<Home />} />
            <Route path="/calculator" element={<Calculator />} />
            <Route path="/quote" element={<Quotes />} />
          </Route>
        </Routes>
      </BrowserRouter>
    </div>
  );
}

export default App;
```
- These routes as created should match the components they are to show and display and you are to put links to each route on the page so that users can navigate to different pages on your webpage

2023-08-30 16:46 UTC, Efiamotu-1 commented on src/route/calculator.js
- [ ] Your layout for each page which are the `Home, Calculator & Quote` should match the provided wireframe as show in the image below. 👍  
![ly](https://github.com/misikir21/mama/assets/89055502/482b6eaa-45c4-469c-9598-32d6efb5caee)

2023-08-30 16:46 UTC, Efiamotu-1 commented on src/route/calculator.js
- In your readme file, please kindly make the following changes:
- [ ] Correct the name of the application to be `Math Magicians` not `Todo list` which is what you currently have 
- [ ] since you do not have a live demo section I kindly suggest you add the appropriate working link to your live demo or you remove the section if this link is not available yet 👍 
- [ ] I kindly suggest you add links to your various accounts such as `Github, LinkedIn & Twitter` to your authors section
- [ ] In your license section I kindly suggest you configure the section correctly and place the appropriate link to your license file 👍

2023-08-31 07:21 UTC, Cabraham1 approved these changes
Hi @misikir21 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 07:25 UTC, merged